=== nicolaikruger/G4TW/www/kraX.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://www.w3schools.com"
		   xmlns="http://www.w3schools.com"
		   elementFormDefault="qualified">

	<!-- definition of simple elements -->
	<xs:element name="n" type="xs:string"/>
	<xs:element name="l" type="xs:decimal"/>
	<xs:element name="s" type="xs:decimal"/>
	<xs:element name="fx" type="xs:decimal"/>
	<xs:element name="fy" type="xs:decimal"/>
	<xs:element name="tx" type="xs:decimal"/>
	<xs:element name="ty" type="xs:decimal"/>

	<!-- definition of attributes -->
	<xs:attribute name="id" type="xs:integer"/>

	<!-- definition of complex elements -->

	<xs:element name="r">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="n"/>
				<xs:element ref="l"/>
				<xs:element ref="s"/>
				<xs:element ref="fx"/>
				<xs:element ref="fy"/>
				<xs:element ref="tx"/>
				<xs:element ref="ty"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="roadCollection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="r"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== nicolaikruger/G4TW/www/kraX.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--
	//////////////////////////////////////
	//	kraX						   	//
	//	Created by G4tw on 2012-02-29. 	//
	//////////////////////////////////////
-->
<roadCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="kraX.xsd">

    <r>
        <n>Kruger</n>
        <s>130.0</s>
        <fx>5.0</fx>
        <fy>6.8</fy>
        <tx>10.1</tx>
        <ty>66.6</ty>
    </r>
    <r>
        <n>Kruger2</n>
        <s>30.0</s>
        <fx>10.1</fx>
        <fy>66.6</fy>
        <tx>150</tx>
        <ty>150</ty>
    </r>

</roadCollection>
